#!/usr/bin/bash

# Javascript debug adapter and configuration for nvim-dap
cd $HOME && mkdir -p ./devDel/microsoft && cd ./devDel/microsoft
git clone https://github.com/microsoft/vscode-node-debug2.git
cd vscode-node-debug2
npm install
NODE_OPTIONS=--no-experimental-fetch npm run build
